INSERT INTO articles (text, color)
VALUES ('Vivamus id sem eu enim fringilla', 'RED'),
       ('Aliquam bibendum orci non nisi', 'GREEN'),
       ('Curabitur mollis turpis ut ligula', 'BLUE'),
       ('Fusce dictum sapien nunc', 'YELLOW'),
       ('Praesent ut augue nec massa tincidunt', 'PURPLE'),
       ('Etiam euismod risus a quam', 'RED'),
       ('Maecenas quis neque ut enim', 'GREEN'),
       ('Donec eleifend nulla id ex hendrerit', 'BLUE'),
       ('Integer tincidunt tellus nec nisi', 'YELLOW'),
       ('Proin fermentum mauris id odio pulvinar', 'PURPLE'),
       ('Nulla rhoncus felis quis mi ullamcorper', 'RED'),
       ('Suspendisse et massa ut mi pharetra', 'GREEN'),
       ('Morbi sagittis ex ac lectus', 'BLUE'),
       ('Nam faucibus euismod nulla eu finibus', 'YELLOW'),
       ('Phasellus at est eget ipsum congue', 'PURPLE');

INSERT INTO users_articles (user_id, article_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (2, 5),
       (3, 6),
       (4, 7),
       (4, 8),
       (4, 9),
       (5, 10),
       (6, 11),
       (7, 12),
       (7, 13),
       (3, 14),
       (2, 15);
